EDGECLOUD-3243 [mcctl] Want More Descriptive Error When Using http instead of https (#1167)
In our regular deployments, MC is fronted by nginx, which returns a
generic 301 response to redirect HTTP to HTTPS. However, this breaks the
POST requests mcctl makes.

Handling this by returning an error message that mcctl can interpret.

  $ mcctl --addr http://console-dev.mobiledgex.net login name=foo password=bar
  Error: login error, Protocol error; console-dev.mobiledgex.net needs HTTPS

  $ mcctl --addr http://console-dev.mobiledgex.net user show
  Error: Bad Request (400), Protocol error; console-dev.mobiledgex.net needs HTTPS